2 unit-теста PairComp и генерация констант
TonitaN/Misc-Lectures pull request #6
Opened 2023-07-19 20:19 UTC by affeeal

Первый пример unit-тестов из ТЗ, второй - с очной части. Вышло объёмно, старался писать наиболее читабельно. Для генерации констант буду менять сначала букву, а затем - число.

Далее берусь за реализацию `PairComp`. Идейно всё представляю: рассматриваем переменные уравнения, ищем места где или пременная соседствует слева с первой константой, или справа - со второй, или с какой-то другой переменной, и запоминаем соответствующие подстановки и накладываемые рестрикции (также учитываем обращение переменной в ε). Если, например, для переменой `x` есть `n1` подстановок, для `y` - `n2` и для `z` - `n3`, то получаем` n1 * n2 * n3` новых уравнений. Каждое из них, далее, нужно обработать: удалить совпадающие префиксы и постфиксы, проверить актуальность индексных уравнений и рестрикций, добавить новые рестрикции при необходимости - всё это не в именно таком порядке, а вообще.

Также в unit-тестах проверется строгий порядок рестрикций. Думаю, я смогу это обеспечить лексикографической сортировкой. Всё больше причин её скорее написать :)

2023-07-19 20:52 UTC, TonitaN commented
Не совсем точно про декартово произведение подстановок: не зря же в рестрикции введена возможность OR-условий (КНФ).
Например, уравнение: `X Y a = abb X`. `PairComp b a` порождает случаи перекрёстных вхождений:
- `X` начинается на `a` (условие 1)
- `X` кончается на `b` И `Y` начинается на `a` (условие 2) - отрицание этого условия порождает композитный OR-блок (нетривиальный дизъюнкт)

То есть, хотя для `Y` есть две возможности (начинаться на `a` или нет), а для `X` четыре, всего получается четыре случая - выполнение условия 1, условия 2, обоих или ни одного. Поэтому имеет смысл отталкиваться от кейсов перекрёстных вхождений, и именно их перемножать, иначе есть риск нарваться на большое количество одинаковых по существу случаев.

Второй момент - когда нужно учитывать обращение переменной в пустое слово? Не всегда - иначе число случаев возрастёт слишком сильно. Но если есть длинный блок из примыкающих друг к другу переменных в разных сочетаниях (без констант или с одной константой в блоке, причём встречающейся в сжимаемой паре), тогда число случаев может быть достаточно велико. К примеру, попробуйте понять, какие комбинации подстановок актуальны для уравнения:
`XYbZaZb = XXaYYZ` и сжатия `ab`

2023-07-19 21:14 UTC, TonitaN requested changes
Нужно аккуратно отследить изменения в блоке, контролирующем непустоту переменных.

2023-07-19 21:14 UTC, TonitaN commented on SummerPSI/InteractiveJez/Unittests.ref
> +            (/* No index equations */)
Отсутствие новых уравнений на индексы - смелое допущение в ТЗ, которая может оказаться и эвристикой (а может - ошибкой). При аккуратной обработке блока рестрикций, кажется, его можно принять. Но вообще-то, если в уравнении есть и составляющие буквы, и новая - возможно, появление уравнения на индексы, которое бы фиксировало эту связь, имеет определённый смысл хотя бы в режиме дебага.

2023-07-19 21:14 UTC, TonitaN commented on SummerPSI/InteractiveJez/Unittests.ref
> +              (OR (not empty (Var 'Y')))
Если мы уже достали какую-то константу из значения `Y`, то предположение о непустоте может сломаться.

2023-07-19 21:14 UTC, TonitaN commented on SummerPSI/InteractiveJez/Unittests.ref
> +      ('Z' 0)
Тут как раз тот самый индекс 0 у свежей константы, который может усложнить жизнь.

2023-07-19 21:14 UTC, TonitaN commented on SummerPSI/InteractiveJez/Unittests.ref
> +          /* (Var 'Y') doesn't end with ('A' 0) and (Var 'X') is empty */
Тут этот случай, как и следующий, не являются критически важными - по перекрёстным вхождениям они эквивалентны случаям 4 и 2. Но мне понравилось, как в случае 6 (следующем) вы красиво сократили константы.

2023-07-21 12:45 UTC, TonitaN commented
Теперь есть и точный алгоритм перебора по пустым подстановкам. В процессе его формулировки появилась заготовка леммы, которую пока принимаем за данность, но когда-нибудь доказать будет нужно.
Там есть один важный момент: рекурсивный запуск PairComp после пустой подстановки. Либо мы делаем перебор по всем комбинациям пустых подстановок сразу и потом рассматриваем строго непустые, либо мы рекурсивно запускаем весь алгоритм, выделяя по очереди существенно пустые подстановки (тогда обязательно нужно навесить рестрикцию по дополнительной ветке, что такая-то переменная непуста, иначе будет очень много повторов). Второе решение мне нравится больше.

2023-07-21 19:30 UTC, TonitaN commented
Обновлён раздел про модификацию рестрикций при PairComp.

2023-07-25 21:45 UTC, TonitaN commented
Оффтопик: добавлен подробный раздел про сжатие блоков (последний) и обработку рестрикций в них. Там есть тонкость с ветвлением на пустые префиксы и суффиксы по независимой рестрикции, а в остальном ничего особенного.

ТЗ размером в 19 страниц на одно практическое задание мне пока ещё писать не доводилось, это впервые 👀
Впрочем, задача того достойна.

2023-08-08 09:30 UTC, affeeal commented on SummerPSI/InteractiveJez/PairComp.ref
> +$ENTRY Go {
`Unittests.ref` получился настолько большим, что придётся разделять функции по разными файлам. Сюда вынесено всё относящееся к `PairComp`, но пока оно не работает. Нужно аккуратно подключить зависимости.

2023-08-13 14:08 UTC, affeeal commented
В итоге, всё разбито на четыре единицы трансляции: `Unittests.ref`, `Main.ref`, `Auxiliaries.ref` и `HigherOrder.ref`. В первой - `unit`-тесты и их запуск, во второй - вся бизнес-логкика, в третьей - вспомогательные функции, а в последней - функции высших порядков. `Unit`-тесты получилсь объёмными, поэтому при запуске необходим флаг `-V2`. Помимо того, и `Unittests.ref`, и `Main.ref` требуют включения `HigherOrder.ref`, поэтому итоговый запуск програмы выглядит примерно так:
```
refgo Preprocess_Inline Main;
refc Main_INLINED;
refgo Preprocess_Inline Unittests;
refc Unittests_INLINED;
refgo Unittests_INLINED+Main_INLINED+Auxilaries -V2;
```

2023-08-14 00:10 UTC, affeeal commented
Кажется, получилось корректно обрабатывать и нетривиальные дизъюнкты в `BlockComp`. Не стал ветвиться в `GenBlockOptionSets`, а подобно происходящему в `NormalizePairOption` для каждой подстановки опции вынуждаю невыполнение противоречащих рестрикций. Затем проверяю получившиеся ограничения на совместность и, наконец, добавляя к получившимся `forced`-дизъюнктам ограничения опции удаляю тривиально выполняющиеся дизъюнкты и рестрикции коллапсирующих в пустоту или блок подстановок. Модифицировал 4-й `unit`-тест `BlockComp`, добавив такие дизъюнкты.

2023-08-14 13:50 UTC, affeeal commented
Кажется, готово. Старался всё протестировать - багов не обнаружил. В самом `Main.ref` сейчас мало комментариев; хотел все решения подробно расписать уже в отчёте.

2023-08-17 14:47 UTC, affeeal commented
Теперь нетривиальные ограничения, содержащие избыточные рестрикции, удаляются.

2023-08-19 09:39 UTC, TonitaN approved these changes
Прекрасная работа. Вливаю.

2023-08-19 09:39 UTC, TonitaN commented on SummerPSI/InteractiveJez/HigherOrder.ref
> +RecSubst {
Строго говоря, это не функция высшего порядка, потому что нет Mu. И её можно спокойно вызывать из зависимого модуля, без инлайна.

2023-08-19 09:39 UTC, TonitaN commented on SummerPSI/InteractiveJez/Main.ref
> +    == False
Небольшое усовершенствование кодстайла: извлекать из рестрикции пятёрку (база)(переменная)(константа)(переменная)(константа). Где база: empty, ends, starts, union (тогда она даже сразу будет рассортирована по алфавиту). Если у нас тривиальный дизъюнкт, тогда первые переменная и константа отсутствуют; если empty - то отсутствуют вообще все константы. И дальше тупо сравнивать лексикографически, передавая сравнению подходящую функцию для каждого типа элементов. Может сильно изменить объём кода к лучшему.

2023-08-19 09:39 UTC, TonitaN commented on SummerPSI/InteractiveJez/Main.ref
> +*/
Здесь чувствуется дефицит функций высшего порядка: схема одна, но с несколькими "дырками" (параметрами ФВП). Когда-нибудь отрефакторим.

2023-08-19 09:40 UTC, merged

2023-08-19 12:49 UTC, affeeal commented on SummerPSI/InteractiveJez/Main.ref
> +*/
Согласен. Эта огромная , по сути, захардкоженная функция мне не нравится больше всего. Хотелось бы в будущем её отрефакторить.